### ISSUE TITLE
use class-norm

### ISSUE THREAD

**Issue by HanAccount** [universome/czsl#5]
Hi! 
When I used class-norm in my code, I found that the accuracy dropped a lot.
Here is my code.
![Screenshot from 2022-03-30 20-46-29](https://user-images.githubusercontent.com/87269265/160837602-66e76bf1-ad18-4724-96a2-9f9486f1ad95.png)
In my method, the AwA2 data set reduces the accuracy considerably.
such as 60% --> 45%
Am I using the wrong method?
thanks!

**Comment by universome** [comment]
Hi, Han! I am sorry, I missed this issue somehow. Could you please how your method looks like? It might be the case that you need to tune the hyper-parameters for it...

Also, we didn't try using it for other methods, so I am not sure how much tuning one would need there.
